name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20  # Gunakan versi Node.js yang sesuai

    - name: Install Dependencies
      run: npm install

    - name: Build and Release
      uses: samuelmeuli/action-electron-builder@v1
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        # Opsi tambahan jika dibutuhkan
      env:
        NODE_OPTIONS: '--max_old_space_size=4096'
