name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14  # Gunakan versi Node.js yang sesuai

    - name: Install Dependencies
      run: npm install

    - name: Publish releases
      env:
          # These values are used for auto updates signing
         github_token: ${{ secrets.GH_TOKEN }}
      run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always --win --mac --linux
